version: '3.4'

services:
  obecto.perper.fabric:
    environment:
    - IGNITE_QUITE=false
    build:
      context: ../perper
      dockerfile: docker/Dockerfile
    ports:
    - "10800:10800"
    - "40400:40400"