version: '3.4'

services:
  obecto.perper.fabric:
    image: obecto/perper-fabric:alpha
  apocryph.dao.bot.core:
    image: ${DOCKER_REGISTRY-}apocryphdaobotcore
    build:
      context: ../
      dockerfile: core/Apocryph.Dao.Bot.Core/Dockerfile
