name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      perper:
        image: obecto/perper-fabric:0.7.1
        ports:
          - 10800:10800
          - 40400:40400
  
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: 'test/Apocryph.Dao.Bot.Tests/appsettings.Development.json'
      env:
        Discord.AuthToken: ${{ secrets.DISCORD_AUTH_TOKEN }}
        Dao.CoreTeamVotingContractAddress: '0x38Ba6a12Ab9537e718d3214beA6643FFDA7D3E69'
        Dao.ApocryphDaoVotingContractAddress: '0xF1eBacf9656fB06B837C1D1a9cE9E06E2897Bcf8'
        Ethereum.Web3Url: ${{ secrets.ETH_WEB3_URL }}
        Ethereum.TokenAddress: '0x0d2cb6d6392114def2f1e93a6ee830ae0cad683d'
    - name: Test
      run: dotnet test --no-build --verbosity normal
      

    
